PrimusCapital.Operaciones/Controllers/DashboardController.cs
using PrimusCapital.Operaciones.Service.Service;
using System.Web.Mvc;

namespace PrimusCapital.Operaciones.Controllers
{
    public class DashboardController : Controller
    {
        private readonly OperacionesServices _op;

        public DashboardController(OperacionesServices op)
        {
            _op = op;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult GuardaRecepcion(string nroOper)
        {
            return Json(_op.RegistroRecepcion(nroOper), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult ObtieneOperacionesEnCurso()
        {
            return Json(_op.ObtieneOperEnCurso(), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult ObtieneOperacionesAprobadas()
        {
            return Json(_op.ObtieneOperAprobadas(), JsonRequestBehavior.AllowGet);
        }
    }
}

PrimusCapital.Operaciones/Views/Dashboard/Index.cshtml
@{
    ViewBag.Title = "Operaciones";
}
<style>
    * {
        font-family: 'open sans';
    }

    #contain {
        height: 695px;
        overflow-y: scroll;
    }

    #table_scroll {
        width: 100%;
        /*margin-top: 100px;*/
        /*margin-bottom: 100px;*/
    }

        #table_scroll tbody td {
            padding: 5px;
            /*background-color: #7fe55e;*/
            /*color: #fff;*/
        }

    #table_fixed thead th {
        padding: 5px;
        /*background-color: #b90be0;*/
        /*color: #fff;*/
        font-weight: 100;
    }

    #table-encurso tbody td {
        padding: 5px;
    }

    fieldset.scheduler-border {
        border: 1px groove #ddd !important;
        padding: 0 1.4em 1.4em 1.4em !important;
        margin: 0 0 1.5em 0 !important;
        -webkit-box-shadow: 0px 0px 0px 0px #000;
        box-shadow: 0px 0px 0px 0px #000;
    }

    legend.scheduler-border {
        font-size: 1.2em !important;
        font-weight: bold !important;
        text-align: left !important;
        width: auto;
        padding: 0 10px;
        border-bottom: none;
    }

    .flipclock {
        padding-left: 700px;
        /*37%*/
        zoom: 0.3;
        -moz-transform: scale(0.3);
    }
</style>

<div class="page-wrapper">
    <div class="row">
        <div class="col-md-7 contenedor-encurso">
            <fieldset class="scheduler-border">
                <legend class="scheduler-border">En Curso</legend>

                <div style="height:738px; overflow-y:auto;">
                    <table class="table color-bordered-table primary-bordered-table">
                        <thead>
                            <tr>
                                <th class="text-center">Id</th>
                                <th class="text-center">Documento</th>
                                <th class="text-center">Estado</th>
                                <th class="text-center">Visador</th>
                                <th class="text-center">Ingreso</th>
                                <th class="text-center">Recepción</th>
                                <th class="text-center">Asignación</th>
                                <th class="text-center">Excepción</th>
                            </tr>
                        </thead>
                        <tbody id="tbody-encurso"></tbody>
                    </table>
                </div>
            </fieldset>
        </div>

        <!--***** Separador *****-->

        <div class="col-md-5 contenedor-aprobadas">
            <fieldset class="scheduler-border">
                <legend class="scheduler-border">Aprobadas</legend>
                <table class="table color-bordered-table muted-bordered-table" style="margin-bottom:0px;" border="0" id="table_fixed">
                    <thead>
                        <tr>
                            <th class="text-center" width="9%">Id</th>
                            <th class="text-center" width="28%">Documento</th>
                            <th class="text-center" width="15%">Visador</th>
                            <th class="text-center" width="18%">Ingreso</th>
                            <th class="text-center" width="17%">Aprobada</th>
                            <th class="text-center">Tiempo</th>
                        </tr>
                    </thead>
                </table>
                <div id="contain">
                    <table class="table color-bordered-table muted-bordered-table" border="0" id="table_scroll">
                        <tbody id="tbody-aprobadas"></tbody>
                    </table>
                </div>
            </fieldset>
        </div>
    </div>
</div>


@section scripts{
    <script src="~/Scripts/Dashboard/formatoNumeros.js"></script>
    <script>
        $(document).ready(function () {
            $('.input-operacion').change(function () {
                var nroOper = $('.input-operacion').val();

                accionSpinner.Load('.contenedor-encurso', '', 'facebook');
                $.ajax({
                    method: 'POST',
                    url: '@Url.Action("GuardaRecepcion", "Dashboard")',
                    data: { nroOper: nroOper }
                }).done(function (data) {
                    if (data == true) {
                        $('.input-operacion').val('');
                        CargaListaOperEnCurso();
                    } else {
                        $('.input-operacion').val('');
                    }
                }).fail(function () {
                    accionSpinner.ErrorConexion();
                }).always(function () {
                    accionSpinner.Hide('.contenedor-encurso');
                });
            });//Fin input-Operacion

            CargaListaOperEnCurso();
            CargarListaAprobadas();
            //var count = 0;
            setInterval(function () {
                CargaListaOperEnCurso();
                CargarListaAprobadas();
                //count = count + 1;
                //console.log("contador " + count);
            }, 300000);


            function CargaListaOperEnCurso() {
                accionSpinner.Load('.contenedor-encurso', '', 'facebook');
                $.ajax({
                    method: 'GET',
                    url: '@Url.Action("ObtieneOperacionesEnCurso", "Dashboard")'
                }).done(function (data) {
                    $('#tbody-encurso').html('');
                    var filas = '';
                    $.each(data, function (i, item) {
                        var fchIngreso = item.FchIngreso == null ? '-' : moment(item.FchIngreso).format("DD-MM-YYYY HH:mm");
                        var fchRecepcion = item.FchRecepcion == null ? '-' : moment(item.FchRecepcion).format("DD-MM-YYYY HH:mm");
                        var fchAsignacion = item.FchAsignacion == null ? '-' : moment(item.FchAsignacion).format("DD-MM-YYYY HH:mm");
                        var fchExcepcion = item.FchExcepcion == null ? '-' : moment(item.FchExcepcion).format("DD-MM-YYYY HH:mm");

                        filas += '<tr>';
                        filas += '<td class="text-center">' + item.IdSimulaOper + '</td>';
                        filas += '<td class="text-center">' + item.Documento + '</td>';
                        filas += '<td class="text-center">' + item.Estado + '</td>';
                        filas += '<td class="text-center">' + item.Visador + '</td>';
                        filas += '<td class="text-center" width="10%">' + fchIngreso + '</td>';
                        filas += '<td class="text-center" width="10%">' + fchRecepcion + '</td>';
                        filas += '<td class="text-center" width="10%">' + fchAsignacion + '</td>';
                        filas += '<td class="text-center" width="10%">' + fchExcepcion + '</td>';
                        filas += '</tr>';
                    });

                    $('#tbody-encurso').append(filas);
                }).fail(function () {
                    accionSpinner.ErrorConexion();
                }).always(function () {
                    accionSpinner.Hide('.contenedor-encurso');
                });
            };//Fin function

            function CargarListaAprobadas() {
                accionSpinner.Load('.contenedor-aprobadas', '', 'facebook');
                $.ajax({
                    method: 'GET',
                    url: '@Url.Action("ObtieneOperacionesAprobadas", "Dashboard")'
                }).done(function (data) {
                    $('#tbody-aprobadas').html('');
                    var filas = '';
                    $.each(data, function (i, item) {
                        var fchIngreso = item.FchIngreso == null ? '-' : moment(item.FchIngreso).format("DD-MM-YYYY HH:mm");
                        var fchAprobacion = item.FchAprobacion == null ? '-' : moment(item.FchAprobacion).format("DD-MM-YYYY HH:mm");

                        filas += '<tr>';
                        filas += '<td class="text-center" width="9%">' + item.IdSimulaOper + '</td>';
                        filas += '<td class="text-center" width="28%">' + item.Documento + '</td>';
                        filas += '<td class="text-center" width="15%">' + item.Visador + '</td>';
                        filas += '<td class="text-center" width="18%">' + fchIngreso + '</td>';
                        filas += '<td class="text-center" width="20%">' + fchAprobacion + '</td>';
                        filas += '<td class="text-center">' + formatoNumero(item.Horas, 2, ',', '.') + '</td>';
                        filas += '</tr>';
                    });

                    $('#tbody-aprobadas').append(filas);
                }).fail(function () {
                    accionSpinner.ErrorConexion();
                }).always(function () {
                    accionSpinner.Hide('.contenedor-aprobadas');
                });
            };//Fin function

        });//Fin Document
    </script>


    <!--AutoScrollTable-->
    <script>
        $(document).ready(function () {
            pageScroll();
            $("#contain").mouseover(function () {
                clearTimeout(my_time);
            }).mouseout(function () {
                pageScroll();
            });

            getWidthHeader('table_fixed', 'table_scroll');

        });

        var my_time;
        function pageScroll() {
            var objDiv = document.getElementById("contain");
            objDiv.scrollTop = objDiv.scrollTop + 1;
            if ((objDiv.scrollTop + 695) == objDiv.scrollHeight) {
                objDiv.scrollTop = 0;
            }
            my_time = setTimeout('pageScroll()', 25);
        }

        function getWidthHeader(id_header, id_scroll) {
            var colCount = 0;
            $('#' + id_scroll + ' tr:nth-child(1) td').each(function () {
                if ($(this).attr('colspan')) {
                    colCount += +$(this).attr('colspan');
                } else {
                    colCount++;
                }
            });

            for (var i = 1; i <= colCount; i++) {
                var th_width = $('#' + id_scroll + ' > tbody > tr:first-child > td:nth-child(' + i + ')').width();
                $('#' + id_header + ' > thead th:nth-child(' + i + ')').css('width', th_width + 'px');
            }
        }
    </script>

}

PrimusCapital.Operaciones/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link rel="icon" href="~/Content/TemaForest/assets/images/logo/favicon.png" type="image/x-icon" />
    <link href="~/Content/TemaForest/assets/plugins/bootstrap/css/bootstrap-edit.css" rel="stylesheet" />
    <link href="~/Content/fontawesome/all.css" rel="stylesheet" />

    <!-- Date picker plugins css -->
    <link href="~/Content/TemaForest/assets/plugins/bootstrap-datepicker/bootstrap-datepicker.min.css" rel="stylesheet" type="text/css" />

    <!--Custom CSS-->
    <link href="~/Content/TemaForest/css/style.css" rel="stylesheet" />
    <link href="~/Content/TemaForest/css/style-custom.css" rel="stylesheet" />
    <!--/Custom CSS-->
    <link href="~/Content/TemaForest/css/colors/blue.css" rel="stylesheet" />

    <!--DataTable-->
    <link href="~/Content/DataTables/css/jquery.dataTables.css" rel="stylesheet" />
    <link href="~/Content/DataTables/css/select.dataTables.css" rel="stylesheet" />
    <link href="~/Content/DataTables/css/dataTables.jqueryui.css" rel="stylesheet" />
    <link href="~/Content/DataTables/css/jquery.dataTables.yadcf.css" rel="stylesheet" />
    <link href="~/Content/DataTables/css/buttons.dataTables.min.css" rel="stylesheet" />
    <link href="~/Content/TemaForest/assets/plugins/Datatable/responsive.dataTables.min.css" rel="stylesheet" />

    <!--/DataTable-->
    <!--Tooltipster-->
    <link href="~/Content/TemaForest/assets/plugins/tooltipster/css/tooltipster.bundle.min.css" rel="stylesheet" />
    <!--/Tooltipster-->
    <!--Select2-->
    <link href="~/Content/TemaForest/assets/plugins/select2/dist/css/select2.min.css" rel="stylesheet" />
    <!--/Select2-->
    <!--toastr | waitme-->
    <link href="~/Content/waitMe.min.css" rel="stylesheet" />
    <link href="~/Content/toastr.css" rel="stylesheet" />
    <!--/toastr | waitme-->
    <!--File-Input-->
    <link href="~/Content/TemaForest/assets/plugins/bootstrap-fileinput/css/fileinput.min.css" rel="stylesheet" />
    <!--/File-Input-->
    <!--FlipClock-->
    <link href="~/Content/TemaForest/assets/plugins/FlipClock/css/flipclock.css" rel="stylesheet" />
    <link href="~/Content/TemaForest/assets/plugins/FlipClock/css/reloj24.css" rel="stylesheet" />
    <!--/FlipClock-->

    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body style="background:#eef5f9">
    @Html.Partial("_Navbar")

    <div class="container-fluid" @*style="margin-bottom:5% !important"*@>
        @RenderBody()
    </div>

    <footer class="footer">
        <p class="text-muted text-center footer-text small">&copy; @DateTime.Now.Year - Departamento TI, Primus Capital S.A.</p>
    </footer>
    <!--Scripts-->
    <!-- jQuery first, then Popper.js, then Bootstrap JS in orden -->
    <script src="~/Content/TemaForest/assets/plugins/jquery/jquery.min.js"></script>
    <script src="~/Content/TemaForest/assets/plugins/bootstrap/js/popper.min.js"></script>
    <script src="~/Content/TemaForest/assets/plugins/bootstrap/js/bootstrap.js"></script>
    <script src="~/Content/TemaForest/assets/plugins/bootstrap/js/bootstrap-select.min.js"></script>

    <!--DataTable-->
    <script src="~/Content/TemaForest/assets/plugins/Datatable/jquery.dataTables.min.js"></script>
    <script src="~/Content/TemaForest/assets/plugins/Datatable/dataTables.responsive.min.js"></script>
    <script src="~/Content/TemaForest/assets/plugins/Datatable/dataTables.select.min.js"></script>
    <!--/DataTable-->
    <!--Tooltipster-->
    <script src="~/Content/TemaForest/assets/plugins/tooltipster/js/tooltipster.bundle.min.js"></script>
    <!--/Tooltipster-->
    <!--Select2-->
    <script src="~/Content/TemaForest/assets/plugins/select2/dist/js/select2.full.js"></script>
    <script src="~/Content/TemaForest/assets/plugins/select2/dist/js/i18n/es.js"></script>
    <!--/Select2-->
    <!--toastr | waitme-->
    <script src="~/Scripts/waitMe.min.js"></script>
    <script src="~/Scripts/toastr.js"></script>
    <!--/toastr | waitme-->
    <!-- slimscrollbar scrollbar JavaScript -->
    <script src="~/Content/TemaForest/js/jquery.slimscroll.js"></script>
    <!--Wave Effects -->
    <script src="~/Content/TemaForest/js/waves.js"></script>
    <!--Menu sidebar -->
    <script src="~/Content/TemaForest/js/sidebarmenu.js"></script>
    <!--stickey kit -->
    <script src="~/Content/TemaForest/assets/plugins/sticky-kit-master/dist/sticky-kit.min.js"></script>
    <script src="~/Content/TemaForest/assets/plugins/sparkline/jquery.sparkline.min.js"></script>
    <!--Custom /preload/ JavaScript -->
    <script src="~/Content/TemaForest/js/custom.js"></script>
    <!-- Date Picker Plugin JavaScript -->
    <script src="~/Content/TemaForest/assets/plugins/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
    <script src="~/Content/TemaForest/assets/plugins/bootstrap-datepicker/bootstrap-datepicker.es.js"></script>
    <!-- Date Picker Plugin JavaScript -->
    <script src="~/Scripts/moment.js"></script>
    <script src="~/Scripts/moment-with-locales.js"></script>
    <script src="~/Content/TemaForest/assets/plugins/Datatable/datetime-moment.js"></script>
    <!--File-Input--> <!--No se utiliza-->
    @*<script src="~/Content/TemaForest/assets/plugins/bootstrap-fileinput/js/fileinput.js"></script>
        <script src="~/Content/TemaForest/assets/plugins/bootstrap-fileinput/js/fileinput_locale_es.js"></script>
        <script src="~/Content/TemaForest/assets/plugins/bootstrap-fileinput/js/fileinputOption.js"></script>*@
    <!--/File-Input-->
    <!--Valida Rut-->
    <script src="~/Scripts/Utilidades/jquery.Rut.js"></script>
    <!--/Valida Rut-->
    <script src="~/Content/TemaForest/js/formatoNumero.js"></script>
    <script src="~/Content/TemaForest/js/validation.js"></script>
    <!--Moment-->
    <script src="~/Content/TemaForest/assets/plugins/moment/moment.js"></script>
    <script src="~/Content/TemaForest/assets/plugins/moment/moment-with-locales.js"></script>
    <!--/Moment-->
    <script src="~/Scripts/Utilidades/funcionSpinner.js"></script>
    <!--FlipClock-->
    <script src="~/Content/TemaForest/assets/plugins/FlipClock/js/flipclock.js"></script>
    <script src="~/Content/TemaForest/assets/plugins/FlipClock/js/reloj24.js"></script>
    <!--/FlipClock-->
    <!--Toastr Options-->
    <script>
        $(document).ready(function () {
            toastr.options = {
                "closeButton": false,
                "debug": false,
                "newestOnTop": true,
                "progressBar": false,
                "positionClass": "toast-top-center",
                "preventDuplicates": false,
                "onclick": null,
                "showDuration": "1000",
                "hideDuration": "1000",
                "timeOut": "3500",
                "extendedTimeOut": "1000",
                "showEasing": "swing",
                "hideEasing": "linear",
                "showMethod": "fadeIn",
                "hideMethod": "fadeOut"
            };
            moment.locale("es");
        
            
            //var clock = new FlipClock($('.your-clock'), {
            //    // ... your options here
            //});
        
        });
        var clock = $('.flipclock').FlipClock({
            //clockFace: 'DailyCounter',
            clockFace: 'TwentyFourHourClock',
            language: 'spanish',
        });
    </script>

    <!--/Scripts-->
    @RenderSection("scripts", required: false)
</body>
</html>

PrimusCapital.Operaciones/Views/Shared/_Navbar.cshtml
<style>
    .square0 {             
        float: left;             
        border-bottom: 61px solid #00b050;             
        border-left: 114px solid #1976d2;         
    }
    .flipclock{
        padding-left:700px;
        /*37%*/
        zoom: 0.3;
        -moz-transform: scale(0.3);
        /*padding-top:25px;*/
    }
</style>

<div class="preloader">
    <svg class="circular" viewBox="25 25 50 50">
        <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" />
    </svg>
</div>
<header class="topbar">
    <nav class="navbar top-navbar navbar-expand-md navbar-light">
        <!-- ============================================================== -->
        <!-- Logo -->
        <!-- ============================================================== -->
        <div class="navbar-header">
            <a class="navbar-brand" href="@Url.Action("Index","Dashboard")">
                <b>
                    <!-- Logo icon -->
                    <img src="~/Content/TemaForest/assets/images/logo/Logo_Parte1.png" alt="homepage" class="light-logo" style="padding-top: 0; padding-bottom: 0; height:50px;" />
                </b><!--End Logo icon -->
                <span>
                    <!-- Logo text -->
                    <img src="~/Content/TemaForest/assets/images/logo/Logo_Parte2.png" alt="homepage" class="light-logo" style="padding-top: 0; padding-bottom: 0; height:50px;" />
                </span><!--End Logo text -->
            </a>
        </div>
        <!-- ============================================================== -->
        <!-- End Logo -->
        <!-- ============================================================== -->
        @*<div class="navbar-header">
            <div class="navbar-brand">

                <h4>Operaciones</h4>

            </div>
        </div>*@
        <div class="navbar-collapse">
            <ul class="navbar-nav mr-auto mt-md-0 p-l-20">
               <li>
                   <div class="row">
                       <div class="col-md-12">
                           <input type="text" name="name" value="" class="form-control input-operacion" autofocus />
                       </div>
                       <!--<div class="col-md-6">
                           <h3 class="text-white" style="float:right">Operaciones2</h3>
                       </div>-->
                   </div>
               </li>
                @*<li class="navbar-brand " style="margin-left:400px">
                    <h3 class="text-white">Operaciones</h3>
                </li>*@
            </ul>
            <!-- ============================================================== -->
            <!-- Profile -->
            <!-- ============================================================== my-lg-0-->
            <ul class="navbar-nav">
                @*<li class="nav-item dropdown text-white" style="padding-top:20px !important;padding-right:10px">
                    @DateTime.Now.ToString("dd/MM/yyyy") 
                </li>*@
                <!--<li class="text-white">
                    <div class="square0">
                    </div>
                </li>-->
                <li>
                    <div class="col-md-12">
                        <div class="flipclock"></div>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
</header>